resolver: lts-9.1

packages:
  - clock-app

extra-deps:
  - X11-extras-0.4

nix:
  packages:
    - cairo
    - glib
    - gtk3
    - pango
    - pkgconfig
    - xorg.libX11
    - xorg.libXext
    - xorg.libXrandr
    - xorg.xproto
    - zlib
