name: clock-app
version: 0.1.0.0
category: Applications

synopsis: >
  Toy GTK app that displays a digital clock.
description: >
  A toy Haskell clock app. Demonstrates use of gtk3, cairo,
  pango, async, and STM.

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/clock-app

license:      Apache-2.0
license-file: license.txt

default-extensions:
  - NoImplicitPrelude

executables:
  clock:
    source-dirs: app
    main: clock.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - async
      - base >= 4.9 && < 4.10
      - cairo
      - glib
      - gtk3
      - pango
      - stm
      - time
      - transformers
      - unix
